// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    IndexList: typeof import('./components/IndexList/IndexList.vue')['default']
    Loading: typeof import('./components/base/loading/Loading.vue')['default']
    MusicList: typeof import('./components/music-list/music-list.vue')['default']
    MyHeader: typeof import('./components/header/MyHeader.vue')['default']
    MyTab: typeof import('./components/tab/MyTab.vue')['default']
    NoResult: typeof import('./components/base/no-result/no-result.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Scroll: typeof import('./components/base/scroll/scroll.vue')['default']
    Slider: typeof import('./components/base/slider/slider.vue')['default']
    SongList: typeof import('./components/base/song-list/song-list.vue')['default']
  }
}
